In [2]:
import pandas as pd
import os

In [15]:
os.listdir()

['.ipynb_checkpoints',
 '.~lock.at_prim.xlsx#',
 'at_prim.xlsx',
 'at_primaria.csv',
 'at_primaria.ipynb',
 'Tabla-5b40b18c-f5d4-4f61-9baa-be94c2560b2d.csv',
 'Tabla-87e61456-a19c-438e-ae6b-20af2db68a62.xls']

In [16]:
at_prim = pd.read_excel('at_prim.xlsx')

In [17]:
at_prim

,Año,CCAA,Sexo,Nivel Renta,Situación Laboral,Grandes Grupos,Casos,Casos por mil personas asignadas,Casos por mil personas atendidas,Personas con problemas de salud,Personas con problemas de salud por mil asignadas,Personas con problemas de salud por mil atendidas
0,2011,02-Aragón,Hombre,Sin Clasificar,Otras situaciones,00-14 años,15124.0,162.59,173.38,12709.0,136.62,145.69
1,2011,02-Aragón,Hombre,Sin Clasificar,Otras situaciones,15-34 años,33756.0,241.65,288.89,26912.0,192.66,230.32
2,2011,02-Aragón,Hombre,Sin Clasificar,Otras situaciones,35-64 años,114724.0,405.98,469.04,82976.0,293.63,339.24
3,2011,02-Aragón,Hombre,Sin Clasificar,Otras situaciones,65 y más años,61073.0,509.34,522.23,43847.0,365.68,374.93
4,2011,02-Aragón,Mujer,Sin Clasificar,Otras situaciones,00-14 años,8688.0,98.02,104.54,7658.0,86.40,92.16
...,...,...,...,...,...,...,...,...,...,...,...,...
13330,2019,17-La Rioja,Mujer,Muy baja,Otras situaciones,35-64 años,NaN,NaN,NaN,NaN,NaN,NaN
13331,2019,17-La Rioja,Mujer,Muy baja,Otras situaciones,65 y más años,NaN,NaN,NaN,NaN,NaN,NaN
13332,2019,17-La Rioja,Mujer,Sin Clasificar,Otras situaciones,00-14 años,NaN,NaN,NaN,NaN,NaN,NaN
13333,2019,17-La Rioja,Mujer,Sin Clasificar,Otras situaciones,35-64 años,387.0,916.82,1014.07,228.0,539.35,596.55
13334,2019,17-La Rioja,Mujer,Sin Clasificar,Otras situaciones,65 y más años,3594.0,1119.28,1150.61,2160.0,672.79,691.62

In [18]:
at_prim['Nivel Renta'].value_counts()

<18.000 ? /año          3720
18.000-99.999 ? /año    3638
Muy baja                2779
?100.000 ? /año         2056
Sin Clasificar          1142
Name: Nivel Renta, dtype: int64